function [fitresult, gof] = createFit3(time_section, sample)
%CREATEFIT3(TIME_SECTION,SAMPLE)
%  Create a fit.
%
%  Data for 'test1' fit:
%      X Input : time_section
%      Y Output: sample
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Jul-2019 11:07:00


%% Fit: 'test1'.
[xData, yData] = prepareCurveData( time_section, sample );

% Set up fittype and options.
ft = fittype( 'sin8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.Robust = 'Bisquare';
opts.StartPoint = [3138.05986046403 31.7332591271696 3.11451005044168 1337.20425125833 63.4665182543391 1.48957282654442 220.93358647624 190.399554763017 2.13884262565597 241.304677996541 126.933036508678 0.834437094447816 93.3041104441535 253.866073017357 1.97177412225368 59.823881687028 317.332591271696 1.88790500397646 39.8739347509913 507.732146034713 2.35053287458396 34.5610072645416 380.799109526035 1.88119739267148];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'test1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'sample vs. time_section', 'test1', 'Location', 'NorthEast' );
% Label axes
xlabel time_section
ylabel sample
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'test1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel time_section
ylabel sample
grid on


